const Paths = {
  LOGIN: "login",
  DASHBOARD: "dashboard",
  ORDER: "order",
  ORDER_DETAIL: "order/detail/:id",
  PRODUCT: "product",
  PRODUCT_ACTION: "product/:action",
  PRODUCT_ACTION_UPDATE: "product/:action/:id",
  MASTER_BRAND: "brand",
  MASTER_BRAND_ACTION: "brand/:action",
  MASTER_BRAND_ACTION_UPDATE: "brand/:action/:id",
  MASTER_PAYMENT: "payment",
  MASTER_PAYMENT_ACTION: "payment/:action",
  MASTER_PAYMENT_ACTION_UPDATE: "payment/:action/:id",
  MASTER_CONTENT_BANNER: "content/banner",
  MASTER_CONTENT_BANNER_ACTION: "content/banner/:action",
  MASTER_CONTENT_BANNER_ACTION_UPDATE: "content/banner/:action/:id",
  MASTER_CONTENT_PROMO: "content/promo",
  MASTER_CONTENT_PROMO_ACTION: "content/promo/:action",
  MASTER_CONTENT_PROMO_ACTION_UPDATE: "content/promo/:action/:id",
  MASTER_CONTENT_FEATURE: "content/feature",
  MASTER_CONTENT_FEATURE_ACTION: "content/feature/:action",
  MASTER_CONTENT_FEATURE_ACTION_UPDATE: "content/feature/:action/:id",
  MASTER_CONTENT_FOOTER: "content/footer",
  MASTER_CONTENT_FOOTER_ACTION: "content/footer/:action",
  MASTER_CONTENT_FOOTER_ACTION_UPDATE: "content/footer/:action/:id",
};

export { Paths };
